apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi
  namespace: aws-k8s-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fastapi.iksanhariji.my.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aws-k8s-app
                port:
                  name: http